name: Build
on: [push]
jobs:
  Build-Actions:
    runs-on: ubuntu-latest
    env:
      CPUS: 4
    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Install package
      run: |
        sudo apt-get -y install build-essential flex m4 bison gnat
    - name: Use a stable GNU mirror
      run: |
        sed -i 's,https://ftpmirror.gnu.org,https://mirrors.kernel.org/gnu,g' ./coreboot/util/crossgcc/buildgcc
    - name: Start Building
      run: |
        cd coreboot && make crossgcc && make iasl
    - name: Make package
      run: |
        tar -cvf ./coreboot-xgcc-bin.tar.gz -C ./coreboot ./util/crossgcc/xgcc
    - name: Upload package
      uses: actions/upload-artifact@v2
      with:
        name: coreboot-xgcc-bin.tar.gz
        path: coreboot-xgcc-bin.tar.gz
